# -*- mode: ruby -*-
# vi: set ft=ruby :


require 'yaml'
configuration = YAML.load_file('../config.yaml')

VAGRANT_COMMAND = ARGV[0]

Vagrant.configure(2) do |server|
  server.vm.box = "stage01"
  server.vm.box_check_update = true

  server.vm.network "private_network", ip: "192.168.200.100"

  #server.vm.synced_folder ".", "/vagrant", disabled: false

  server.vm.provider "virtualbox" do |vb|
    vb.name = "hawk122"
    vb.memory = "2048"
  end

  server.vm.provision "shell" do |script|
    script.path = "provision/update-kernel.sh"
    script.args = ["#{configuration['kernel']}"]
  end
end
