# -*- mode: ruby -*-
# vi: set ft=ruby :


require 'yaml'
configuration = YAML.load_file('../config.yaml')

VAGRANT_COMMAND = ARGV[0]

Vagrant.configure(2) do |server|
  server.vm.box = "hawk1222"
  server.vm.box_check_update = true

  server.vm.network "private_network", ip: "192.168.200.100"

  server.vm.provider "virtualbox" do |vb|
    vb.name = "hawk122"
    vb.memory = "2048"
  end
end
