# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
configuration = YAML.load_file('../config.yaml')

Vagrant.configure(2) do |server|
  server.vm.box = "hawk1222"
  server.vm.box_check_update = true

  server.vm.network "private_network", ip: "192.168.200.100"

  server.vm.provider "virtualbox" do |vb|
    vb.name = "hawk122"
    vb.memory = "2048"
  end

  server.vm.provision "shell" do |script|
    script.path = "provision/create-containers.sh"
    script.args = ["#{configuration['ports']['gitlab']}"]
  end
end
