# -*- mode: ruby -*-
# vi: set ft=ruby :

# define config.yaml with content:
#---
#user:
#    name: <user-name: string; e.g.: user>
#    passwd: <some-password: string; e.g.: passw>
#country: <country-code: string; e.g.: hu>
#ports:
#  gitlab: <port-number: number; eg 10000>

require 'yaml'

configuration = YAML.load_file('../config.yaml')

Vagrant.configure(2) do |server|
  server.vm.box = "ubuntu/wily64"
  server.vm.box_check_update = true

  server.vm.provision "shell" do |script|
    script.path = "provision/setup-server.sh"
    script.args = ["#{configuration['user']['name']}", "#{configuration['user']['passwd']}", "#{configuration['country']}"]
  end
end
