# -*- mode: ruby -*-
# vi: set ft=ruby :


#VBoxManage list systemproperties | grep "Default machine folder:"
#VBoxManage setproperty machinefolder


# define config.yaml with content:
#---
#user:
#    name: utamas
#    passwd: some-password
#kernel: v3.14.1-trusty
#service:
#  dns:
#    rootPassword: some-password
#country: hu

require 'yaml'
configuration = YAML.load_file('../config.yaml')

VAGRANT_COMMAND = ARGV[0]

Vagrant.configure(2) do |server|
  server.vm.box = "ubuntu/wily64"
  server.vm.box_check_update = true

  server.vm.network "private_network", ip: "192.168.200.100"

  server.vm.provider "virtualbox" do |vb|
    #vb.name = "sandbox"
    vb.memory = "512"
  end

  server.vm.provision "shell" do |script|
    script.path = "provision/update-kernel.sh"
    script.args = ["#{configuration['user']['name']}", "#{configuration['user']['passwd']}", "#{configuration['country']}", "#{configuration['kernel']}"]
  end
end
